---
- import_tasks: configure.yml

- name: Install certbot
  package:
    name: "certbot={{ certbot_version }}"
    state: present

- name: Install certbot-nginx plugin
  package:
    name: "{{ certbot_nginx_name }}={{ certbot_nginx_version }}"
    state: present

- import_tasks: certificate.yml
  when: domain_name is defined
