---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance-xenial
    image: ubuntu:16.04
  - name: instance-bionic
    image: ubuntu:18.04
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
