---
dependency:
  name: galaxy
driver:
  name: docker
lint: yamllint
platforms:
  - name: instance-xenial
    image: ubuntu:16.04
  - name: instance-bionic
    image: ubuntu:18.04
provisioner:
  name: ansible
  lint: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint: flake8
